- name : set up yum repos for redis
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install redis
  yum:
    name: redis
    state: present
    enablerepo: remi

- name: change the ip 127.0.0.1 to 0.0.0.0
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start reddis service
  systemd:
    state: started
    enabled: yes
    name: redis
