- name: robpshop playook
  hosts: all
  become: yes
  tasks:
    - name: import frontend role
      import_role:
         name: frontend
      when: component == "frontend"
      tags:
        - frontend
