- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Download Azure Artifacts
  include_role:
    name: common
    tasks_from: azure-artifact.yml
  vars:
    ARTIFACT_PATH: /usr/share/nginx/html
    COMPONENT: frontend
    COMPONENT_ID: 0237947c-8a5c-41bb-a2bc-f6ca6e5e2584
    type: frontend

- name: Update Nginx configuration
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Start Nginx Service
  systemd:
    state: started
    enabled: yes
    name: nginx
