- name: cpy AZ repo
  copy:
    src: azure-clirepo.yml
    dest: /etc/yum.repos.d/az-cli.repo

- name: install azure cli
  yum:
    name: ["azure-cli" , "libicu"]
    state: latest

- name: istall azure cli extention
  shell: az extension add --name azure-devops

- name: configure azure cli
  shell: echo {{PAT}} | az devops login

- name: get the latest version
  shel: curl -s curl https://feeds.dev.azure.com/sushmitha771995/instana/_apis/packaging/Feeds/instana/Packages/231ee70c-0b6d-4d95-8b4c-28ab8b84ed1f/versions?api-version=6.1-preview.1 | jq '.value[] | .version+ " " + .views[].name' | grep Local | head -1 | args | awk '{print $1}'
  register: version
- name: download artifacts latest local
  shell: az artifacts universal download \
    --organization "https://dev.azure.com/sushmitha771995/" \
    --project "0c8936fe-4cdc-445e-bd0b-2e7dc0f25a3f" \
    --scope project \
    --feed "instana" \
    --name "cart" \
    --version "{{version.stdout}}" \
    --path .
  args:
    chdir: /tmp
